### ISSUE TITLE
Could not compile on Ubuntu 12.04 32 bit using latest git versions and lastest decklink drivers

### ISSUE THREAD

**Issue by rstanislav** [kierank/broadcastencoder#9]
libobe.a(linsys.o): In function `open_card':
linsys.c:(.text+0x1a3d): undefined reference to`obe_v210_planar_unpack_aligned_ssse3'
linsys.c:(.text+0x1a49): undefined reference to `obe_v210_planar_unpack_aligned_avx'
linsys.c:(.text+0x26de): undefined reference to`obe_downscale_line_mmx'
linsys.c:(.text+0x26f0): undefined reference to `obe_downscale_line_sse2'
libobe.a(video.o): In function`start_filter':
video.c:(.text+0x4d4): undefined reference to `obe_dither_row_10_to_8_sse4'
video.c:(.text+0x4ed): undefined reference to`obe_dither_row_10_to_8_avx'
libobe.a(decklink.o): In function `open_card(decklink_opts_t*)':
decklink.cpp:(.text+0x151c): undefined reference to`obe_downscale_line_mmx'
decklink.cpp:(.text+0x152b): undefined reference to `obe_downscale_line_sse2'
collect2: ld returned 1 exit status
make: **\* [obecli] Error 1
